include:
  - remote: 'https://gitlab.com/peter.saarland/scratch/-/raw/master/ci/templates/version.gitlab-ci.yml'
  - remote: 'https://gitlab.com/peter.saarland/scratch/-/raw/master/ci/templates/release.gitlab-ci.yml'

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /-wip$/
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - version
  - build
  - test
  - release
  - deploy
    
cache:
  key: "$CI_JOB_NAME"
  
variables:
  DOCKER_TLS_CERTDIR: ""

build php7:
  stage: build
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  variables:
    DOCKER_BUILDKIT: 1 
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/php7:$CI_COMMIT_SHA
  script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY --username=gitlab-ci-token --password-stdin
    - docker build --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $IMAGE_TAG -f docker/php7/Dockerfile docker/php7
    - docker push $IMAGE_TAG

build mysql:
  stage: build
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  variables:
    DOCKER_BUILDKIT: 1 
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/mysql:$CI_COMMIT_SHA
  script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY --username=gitlab-ci-token --password-stdin
    - docker build --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $IMAGE_TAG -f docker/mysql/Dockerfile docker/mysql
    - docker push $IMAGE_TAG

# include:
#   - template: Container-Scanning.gitlab-ci.yml

# include:
#   - template: License-Scanning.gitlab-ci.yml
  
# include:
#   - template: Dependency-Scanning.gitlab-ci.yml

# include:
#   - template: SAST.gitlab-ci.yml

test shopware:
  stage: test
  image: docker/compose
  variables:
    TRAEFIK_DOMAIN: traefik.127.0.0.1.xip.io
    APP_DOMAINS: shopware.127.0.0.1.xip.io
  services:
    - docker:19.03.8-dind
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.traefik.yml -f docker-compose.domain.yml up -d
    - curl -fsSL http://traefik.127.0.0.1.xip.io

publish php7:
  stage: release
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY --username=gitlab-ci-token --password-stdin
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/php7:$CI_COMMIT_SHA || true
    - docker tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/php7:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/php7:latest
    - docker push $CI_REGISTRY_IMAGE/php7:latest
    - docker tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/php7:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/php7:v$(cat VERSION.txt)
    - docker push $CI_REGISTRY_IMAGE/php7:v$(cat VERSION.txt)
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: on_success

publish mysql:
  stage: release
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY --username=gitlab-ci-token --password-stdin
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/mysql:$CI_COMMIT_SHA || true
    - docker tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/mysql:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/mysql:latest
    - docker push $CI_REGISTRY_IMAGE/mysql:latest
    - docker tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/mysql:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/mysql:v$(cat VERSION.txt)
    - docker push $CI_REGISTRY_IMAGE/mysql:v$(cat VERSION.txt)
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: on_success