version: '3.7'
shopware-app:
  ports:
  labels:
    - traefik.enable=true
    - traefik.docker.network=web
    - traefik.primawell.frontend.rule=Host:${APP_DOMAINS:-app.example.com}
    - traefik.primawell.frontend.entryPoints=http,https
    - traefik.primawell.frontend.headers.SSLRedirect=true
    - traefik.primawellport=80
  networks:
    - shopware
    - ${TRAEFIK_NETWORK}

networks:
  shopware:
  ${TRAEFIK_NETWORK}: